### ISSUE TITLE
Add functionality to change quadrature degree in class Contact.

### ISSUE THREAD

**Issue by SarahRo** [Wells-Group/asimov-custom-assemblers#35]
Suggestion: optional input parameter quadrature_degree for function create_distance_map.  If quadrature degree unchanged, check if _qp_ref_facet and _phi_ref_facets already computed (these are the same independent of origin_meshtag).

**Comment by jorgensd** [comment]
Not relevant any longer as contact has been moved to https://github.com/Wells-Group/asimov-contact
